{
 "title": "Peggo Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Peggo API Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "peggo_api_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peggo Pending Batches",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "peggo_pending_batches", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peggo Pending Valsets",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "peggo_pending_valsets", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Peggo Latest Nonce",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "peggo_last_observed_nonce" }
   ]
  },
  {
   "title": "Peggo Last Orchestrator Nonce",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "peggo_last_claim_eth_event_nonce"
    }
   ]
  }
 ]
}